spring:
  application:
    name: baewoo-app

  data:
    mongodb:
      # Using Environment Variables
      uri: mongodb+srv://${MONGO_CLOUD_USER}:${MONGO_CLOUD_PASSWORD}@${MONGO_CLOUD_HOST}/baewoo?retryWrites=true&w=majority

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user

routes:
  baseUri: api
  v1:
    userInfo: ${routes.baseUri}/v1/user
    wordConfig: ${routes.baseUri}/v1/word/config
    word: ${routes.baseUri}/v1/word
    learn: ${routes.baseUri}/v1/learn
  auth:
    whitelist: ${routes.v1.learn}, ${routes.v1.userInfo}
